name: calcetto_tracker
description: App per registrare risultati di calcetto e voti giocatori (Hive - locale)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.0.5
  uuid: ^3.0.7
  intl: ^0.20.2
  image_picker: ^1.1.2        # selezione foto dalla galleria
  path_provider: ^2.1.4       # cartella documenti dell'app
  path: ^1.9.0                # utilità per manipolare path di file
  csv: ^6.0.0             # parsing e generazione CSV
  share_plus: ^10.0.0     # condivisione file (sheet, email, whatsapp...)
  file_picker: ^8.1.2     # selezione file CSV dal dispositivo per import
  shared_preferences: ^2.5.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/shields/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"
